PSFR-1215: Removed the release type from the “Release” column
ministryofjustice/hmpps-resettlement-passport-ui pull request #289
Opened 2024-04-17 10:22 UTC by ashliecodes

2024-04-17 10:42 UTC, peterhippocarter approved these changes

2024-04-17 10:58 UTC, JamesBoobier requested changes
It also needs removing from the profile

2024-04-18 08:01 UTC, peterhippocarter submitted a review, later dismissed

2024-04-18 08:56 UTC, ashliecodes reviewed
All done

2024-04-19 08:35 UTC, JamesBoobier approved these changes

2024-04-19 08:36 UTC, merged